/**
 * Created by haozi on 6/14/2017.
 */

/**
 * 系统功能
 */

export default {
  CHANGE_MARKDOWN: 'CHANGE_MARKDOWN',
  SAVE_POST_LOCALSTORAGE: 'SAVE_POST_LOCALSTORAGE',
  SAVE_POST_SERVER: 'SAVE_POST_SERVER',
  SAVE_POST_SUCCESS: 'SAVE_POST_SERVER_SUCCESS',
  SAVE_POST_LOCALSTORAGE_SUCCESS: 'SAVE_POST_LOCALSTORAGE_SUCCESS',
}